# Generated by Django 4.1.13 on 2025-04-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker_app", "0001_initial"),
    ]

    operations = [
        # Skipping the alteration of the 'id' field for the 'activity' model
        # migrations.AlterField(
        #     model_name="activity",
        #     name="id",
        #     field=models.BigAutoField(
        #         auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
        #     ),
        # ),
        # Skipping the alteration of the 'id' field for the 'leaderboard' model
        # migrations.AlterField(
        #     model_name="leaderboard",
        #     name="id",
        #     field=models.BigAutoField(
        #         auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
        #     ),
        # ),
        # Skipping the alteration of the 'id' field for the 'team' model
        # migrations.AlterField(
        #     model_name="team",
        #     name="id",
        #     field=models.BigAutoField(
        #         auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
        #     ),
        # ),
        # Skipping the alteration of the 'id' field for the 'user' model
        # migrations.AlterField(
        #     model_name="user",
        #     name="id",
        #     field=models.BigAutoField(
        #         auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
        #     ),
        # ),
        # Skipping the alteration of the 'id' field for the 'workout' model
        # migrations.AlterField(
        #     model_name="workout",
        #     name="id",
        #     field=models.BigAutoField(
        #         auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
        #     ),
        # ),
    ]
